### PR TITLE
exclude unnecessary file from codecov 

### LINKED ISSUE #537: remove unneeded files from codecov check
e.g., 
.md,
.sh
.bat
.cmd
LICENSE
NOTICE 
etc..

### PR DESCRIPTION
**Pull request by jixuan1989**
fix #537 
exclude: 
  - "**/pom.xml"
  - "**/*.md"
  - "**/*.sh"
  - "**/*.cmd"
  - "**/*.bat"
  - "**/*.yml"
  - ".mvn"
  - "mvnw"
  - "NOTICE"
  - "NOTICE-binary"
  - "License"
  - "LICENSE-binary"

### CODE REVIEW

**Comment by jixuan1989** [comment]
@MyXOF can you check why the UT coverage rate decreased?

**Comment by MyXOF** [comment]
It seems codecov has bug

**Comment by wujysh** [comment]
Is that our UT has random mechanism and the result is not stable?

**Comment by jixuan1989** [comment]
> Is that our UT has random mechanism and the result is not stable?

I do not think so.

**Comment by jixuan1989** [comment]
> It seems codecov has bug

Hm... if so, can you approve this PR?

**Pull request merged**
